### ISSUE TITLE
niv-updater-action causes back references noise in nixpkgs

### ISSUE THREAD

**Issue by FRidh** [knl/niv-updater-action#36]
I recently noticed a lot of references to commits made using this updater action. While I totally see the value for users of the action, the noise can be really annoying for those being referenced. See e.g. (yes, I am creating some noise now myself) https://github.com/NixOS/nixpkgs/pull/97586. As soon as this updater action starts to be used more the back references on the issues become useless.

This is perhaps not the right place to see this fixed, since in the end it is GitHub that adds the references, but practically speaking you are the only ones that can do anything about it.

**Comment by knl** [comment]
Hi @FRidh, thanks for reporting this. I thought I got it fixed with `github_changelog_no_backreferences` option (which defaults to `true`) -- it was raised in the issue #26 and fixed in Release 6: https://github.com/knl/niv-updater-action/releases/tag/v6

From what I see, the references are coming from people using versions older than v6. I'll ping them and ask to update.

**Comment by FRidh** [comment]
Alright, thank you!

**Comment by knl** [comment]
I'm closing this issue since I've contacted everyone with the older version, and the last two release don't cause noise. Please reopen if you spot any issue.
